<?php if (! defined('ABSPATH')) { exit; } ?>
<section class="ssf-process-shell">
    <div class="ssf-process-heading">
        <p class="ssf-process-eyebrow">Sveriges Segelfartygsförbund</p>
        <h1>Ansök om medlemskap</h1>
        <p>Berätta om fartyget och ert fartygsombud. Du kan spara informationen i lugn takt och får en personlig länk för att följa ärendet när ansökan är inskickad.</p>
    </div>
    <form class="ssf-process-form" method="post" enctype="multipart/form-data" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" data-ssf-application-form>
        <input type="hidden" name="action" value="ssf_submit_application">
        <input class="ssf-process-honeypot" type="text" name="website" tabindex="-1" autocomplete="off" aria-hidden="true">
        <?php wp_nonce_field('ssf_application_submit'); ?>
        <div class="ssf-process-progress" aria-label="Formulärsteg"><span data-ssf-progress></span></div>
        <p class="ssf-process-step-count" data-ssf-step-count>Steg 1 av 10</p>

        <fieldset class="ssf-process-step is-active">
            <legend>Välj ansökningsväg</legend>
            <p>Vi använder uppgifterna för att avgöra hur ansökan ska bedömas.</p>
            <label class="ssf-process-choice"><input type="radio" name="application_path" value="standard" required> Fartyget uppfyller måttkraven <small>Över 12 meter i huvuddäck och minst 4 meter brett.</small></label>
            <label class="ssf-process-choice"><input type="radio" name="application_path" value="special"> Fartyget uppfyller inte måttkraven <small>Särskild prövning kan vara möjlig.</small></label>
        </fieldset>

        <fieldset class="ssf-process-step" hidden><legend>Segelfartyg</legend><p>Är fartyget ett segelfartyg eller segelfartyg med hjälpmotor?</p><label class="ssf-process-choice"><input type="radio" name="ship_is_sailing" value="Ja" required> Ja</label><label class="ssf-process-choice"><input type="radio" name="ship_is_sailing" value="Nej"> Nej</label></fieldset>
        <fieldset class="ssf-process-step" hidden><legend>Yrkesfartyg</legend><p>Har fartyget använts eller används det som seglande yrkesfartyg?</p><label class="ssf-process-choice"><input type="radio" name="ship_professional_use" value="Ja" required> Ja</label><label class="ssf-process-choice"><input type="radio" name="ship_professional_use" value="Nej"> Nej</label><p>Är fartyget nybyggt i traditionell stil?</p><label class="ssf-process-choice"><input type="radio" name="ship_traditional_newbuild" value="Ja" required> Ja</label><label class="ssf-process-choice"><input type="radio" name="ship_traditional_newbuild" value="Nej"> Nej</label></fieldset>
        <fieldset class="ssf-process-step" hidden><legend>Fartygets mått</legend><div class="ssf-process-grid"><label>Längd i huvuddäck (meter)<input type="text" name="ship_length" inputmode="decimal" required></label><label>Bredd (meter)<input type="text" name="ship_beam" inputmode="decimal" required></label><label>Djupgående (meter)<input type="text" name="ship_draft" inputmode="decimal"></label></div></fieldset>
        <fieldset class="ssf-process-step" hidden><legend>Registrering</legend><p>Är fartyget registrerat i svenskt skeppsregister?</p><label class="ssf-process-choice"><input type="radio" name="ship_register" value="Ja" required> Ja</label><label class="ssf-process-choice"><input type="radio" name="ship_register" value="Nej"> Nej</label><label>Registreringsnummer <input type="text" name="ship_registry_number"></label></fieldset>
        <fieldset class="ssf-process-step" hidden><legend>Uppgifter om fartyget</legend><div class="ssf-process-grid"><label>Fartygets namn<input type="text" name="ship_name" required></label><label>Fartygstyp<input type="text" name="ship_type" required></label><label>Rigtyp<input type="text" name="ship_rig"></label><label>Byggår<input type="number" min="1000" max="2100" name="ship_build_year"></label><label>Byggplats eller varv<input type="text" name="ship_shipyard"></label><label>Hemmahamn<input type="text" name="ship_home_port"></label></div><label class="ssf-process-choice"><input type="checkbox" name="ship_restoration" value="Ja"> Fartyget är under restaurering</label><label>Kort beskrivning<textarea name="ship_short_description" rows="4" required></textarea></label></fieldset>
        <fieldset class="ssf-process-step" hidden><legend>Historia och användning</legend><label>Historia<textarea name="ship_history" rows="6" required></textarea></label><label>Vad används fartyget till idag?<textarea name="ship_current_use" rows="6" required></textarea></label><label>Fördjupad beskrivning, valfritt<textarea name="ship_description" rows="5"></textarea></label></fieldset>
        <fieldset class="ssf-process-step" hidden><legend>Fartygsombud</legend><div class="ssf-process-grid"><label>Namn<input type="text" name="applicant_name" required></label><label>E-post<input type="email" name="applicant_email" required></label><label>Telefon<input type="tel" name="applicant_phone" required></label><label>Organisation, förening eller rederi<input type="text" name="applicant_organization"></label><label>Adress, valfritt<input type="text" name="applicant_address"></label><label>Webbplats, valfritt<input type="url" name="applicant_website"></label></div></fieldset>
        <fieldset class="ssf-process-step" hidden><legend>Bilagor och bilder</legend><p>Ladda gärna upp bilder och relevanta dokument. Tillåtna filer är JPG, PNG, WEBP och PDF.</p><label>Filer <input type="file" name="ssf_application_files[]" accept=".jpg,.jpeg,.png,.webp,.pdf" multiple></label><p class="ssf-process-help">Bilder får vara högst <?php echo esc_html((string) $settings['max_image_mb']); ?> MB och PDF-filer högst <?php echo esc_html((string) $settings['max_file_mb']); ?> MB.</p></fieldset>
        <fieldset class="ssf-process-step" hidden><legend>Förhandsgranska och skicka</legend><p>Kontrollera att uppgifterna är korrekta. SSF hör av sig om vi behöver kompletteringar.</p><label class="ssf-process-choice"><input type="checkbox" name="confirm_accuracy" value="1" required> Jag intygar att uppgifterna är korrekta.</label><label class="ssf-process-choice"><input type="checkbox" name="privacy_consent" value="1" required> Jag godkänner att SSF behandlar uppgifterna för att hantera ansökan.</label><label class="ssf-process-choice"><input type="checkbox" name="upload_rights" value="1" required> Jag intygar att jag har rätt att ladda upp bilder och bilagor.</label></fieldset>

        <div class="ssf-process-actions"><button type="button" class="ssf-process-button ssf-process-button--secondary" data-ssf-prev hidden>Tillbaka</button><button type="button" class="ssf-process-button" data-ssf-next>Nästa</button><button type="submit" class="ssf-process-button" data-ssf-submit hidden>Skicka ansökan</button></div>
    </form>
</section>
