<?php
if (! defined('ABSPATH')) { exit; }
$template = (array) ($protocol['template'] ?? array());
$application_snapshot = (array) ($protocol['application'] ?? array());
$questions = SSF_Medlemsprocess_Inspection::questions($template);
?>
<article class="ssf-process-shell ssf-inspection-protocol">
    <header class="ssf-process-heading"><p class="ssf-process-eyebrow">Sveriges Segelfartygsförbund</p><h1>Inspektionsprotokoll – medlemsprövning av fartyg</h1><p><?php echo esc_html(($template['name'] ?? '') . ' · version ' . ($template['version'] ?? '')); ?></p></header>
    <dl class="ssf-inspector-application-snapshot"><div><dt>Fartyg</dt><dd><?php echo esc_html($application_snapshot['ship_name'] ?? ''); ?></dd></div><div><dt>Fartygsombud</dt><dd><?php echo esc_html($application_snapshot['applicant_name'] ?? ''); ?></dd></div><div><dt>Datum</dt><dd><?php echo esc_html($protocol['details']['date'] ?? ''); ?></dd></div><div><dt>Plats</dt><dd><?php echo esc_html($protocol['details']['place'] ?? ''); ?></dd></div><div><dt>Signal / reg.nr</dt><dd><?php echo esc_html($application_snapshot['registry_number'] ?? ''); ?></dd></div><div><dt>Närvarande</dt><dd><?php echo esc_html($protocol['details']['attendees'] ?? ''); ?></dd></div><div><dt>Inspektör(er)</dt><dd><?php echo esc_html(implode(', ', wp_list_pluck((array) ($protocol['inspectors'] ?? array()), 'name'))); ?></dd></div></dl>
    <?php foreach ((array) ($template['sections'] ?? array()) as $section) : ?><section class="ssf-status-section"><h2><?php echo esc_html($section['title']); ?></h2><?php foreach ((array) $section['questions'] as $question) : $answer = (array) ($protocol['answers'][$question['id']] ?? array()); ?><div class="ssf-inspector-question"><h3><?php echo esc_html(strtoupper($question['id']) . '. ' . $question['text']); ?></h3><p><strong><?php echo esc_html($answer['selected_option'] ?? 'Ej besvarad'); ?></strong></p><?php if (! empty($answer['comment'])) : ?><p><?php echo nl2br(esc_html($answer['comment'])); ?></p><?php endif; ?><div class="ssf-inspector-photos"><?php foreach ((array) ($protocol['photos'] ?? array()) as $photo) : if (($photo['question_id'] ?? '') !== $question['id'] || 'protocol' !== ($photo['visibility'] ?? '')) { continue; } ?><figure><img src="<?php echo esc_url(SSF_Medlemsprocess_Plugin::instance()->inspector->photo_url($inspection_id, $photo['id'], $photo_token)); ?>" alt="<?php echo esc_attr($photo['caption'] ?: 'Inspektionsbild'); ?>"><?php if ($photo['caption']) : ?><figcaption><?php echo esc_html($photo['caption']); ?></figcaption><?php endif; ?></figure><?php endforeach; ?></div></div><?php endforeach; ?></section><?php endforeach; ?>
    <?php $overview_keys = array_keys((array) ($template['overview_photos'] ?? array())); $overview = array_filter((array) ($protocol['photos'] ?? array()), static function (array $photo) use ($overview_keys): bool { return in_array($photo['question_id'] ?? '', $overview_keys, true) && 'protocol' === ($photo['visibility'] ?? ''); }); if ($overview) : ?><section class="ssf-status-section"><h2>Översiktsbilder</h2><div class="ssf-inspector-photos"><?php foreach ($overview as $photo) : ?><figure><img src="<?php echo esc_url(SSF_Medlemsprocess_Plugin::instance()->inspector->photo_url($inspection_id, $photo['id'], $photo_token)); ?>" alt="<?php echo esc_attr($photo['caption'] ?: ($template['overview_photos'][$photo['question_id']] ?? 'Översiktsbild')); ?>"><figcaption><?php echo esc_html($photo['caption'] ?: ($template['overview_photos'][$photo['question_id']] ?? '')); ?></figcaption></figure><?php endforeach; ?></div></section><?php endif; ?>
    <section class="ssf-status-section"><h2>Sammanfattning / motivering</h2><p><?php echo nl2br(esc_html($protocol['summary'] ?? '')); ?></p></section>
    <aside class="ssf-status-section"><strong>Viktig information</strong><p><?php echo esc_html($template['disclaimer'] ?? ''); ?></p></aside>
    <p><button class="ssf-process-button" type="button" onclick="window.print()">Skriv ut / spara som PDF</button></p>
</article>
