<?php
/** @var SSF_Medlemsprocess_Inspector $this */
if (! defined('ABSPATH')) { exit; }
$user = wp_get_current_user();
?>
<section class="ssf-inspector-shell">
<?php if ('dashboard' === $view) : ?>
    <header class="ssf-inspector-header"><div><p class="ssf-inspector-kicker">SSF medlemsprocess</p><h1>Mina inspektioner</h1><p>Inloggad som <?php echo esc_html($user->display_name); ?></p></div></header>
    <?php if (! $cases) : ?><div class="ssf-inspector-empty"><h2>Inga tilldelade inspektioner</h2><p>När en handläggare tilldelar dig ett aspirantfartyg visas det här.</p></div><?php endif; ?>
    <div class="ssf-inspector-case-list">
    <?php foreach ($cases as $item) : ?>
        <article class="ssf-inspector-case-card"><div><span class="ssf-inspector-number"><?php echo esc_html($item['number']); ?></span><h2><?php echo esc_html($item['title']); ?></h2><p><?php echo ! empty($item['legacy']) ? 'Äldre inspektionsformat' : esc_html(ucfirst(str_replace('_', ' ', $item['record']['status'] ?? 'draft'))); ?></p></div><a class="ssf-process-button" href="<?php echo esc_url($item['url']); ?>">Öppna</a></article>
    <?php endforeach; ?>
    </div>
<?php elseif ('legacy' === $view) : ?>
    <header class="ssf-inspector-case-heading"><a href="<?php echo esc_url($portal_url); ?>">← Mina inspektioner</a><div><p class="ssf-inspector-number"><?php echo esc_html($case['number']); ?></p><h1><?php echo esc_html($case['title']); ?></h1><p>Äldre inspektionsformat · skrivskyddat</p></div></header>
    <section class="ssf-inspector-panel"><h2>Äldre inspektionsrapport</h2><p>Rapporten bevaras i sitt ursprungliga format. Nya inspektioner använder mallversionerade, gemensamma protokoll.</p><?php foreach ($case['reports'] as $report) : $inspection = (array) ($report['inspection'] ?? array()); ?><article class="ssf-inspector-question"><p><strong>Status:</strong> <?php echo esc_html($report['status'] ?? ''); ?></p><?php foreach ((array) ($inspection['checks'] ?? array()) as $key => $answer) : ?><div><strong><?php echo esc_html($key); ?></strong>: <?php echo esc_html($answer['status'] ?? ''); ?><?php if (! empty($answer['comment'])) : ?> – <?php echo esc_html($answer['comment']); ?><?php endif; ?></div><?php endforeach; ?><?php if (! empty($inspection['summary'])) : ?><h3>Sammanfattning</h3><p><?php echo nl2br(esc_html($inspection['summary'])); ?></p><?php endif; ?><?php if (! empty($inspection['recommendation'])) : ?><p><strong>Rekommendation:</strong> <?php echo esc_html($inspection['recommendation']); ?></p><?php endif; ?></article><?php endforeach; ?></section>
<?php else :
    $record = $case['record']; $template = $record['template']; $questions = SSF_Medlemsprocess_Inspection::questions($template);
    $readonly = empty($case['can_edit']); $snapshot = $record['application_snapshot'];
?>
    <?php if (! empty($record['is_test'])) : ?>
        <aside class="ssf-inspector-test-banner" role="status"><div><strong>TESTINSPEKTION</strong><span>Den här inspektionen påverkar inte medlemsärendet.</span></div><a href="<?php echo esc_url($portal_url); ?>">Avsluta test</a><?php if (current_user_can('manage_options')) : ?><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="ssf_delete_test_inspection"><input type="hidden" name="inspection_id" value="<?php echo esc_attr((string) $case['inspection_id']); ?>"><?php wp_nonce_field('ssf_delete_test_inspection_' . $case['inspection_id']); ?><button type="submit" onclick="return confirm('Radera endast denna testinspektion?')">Radera testinspektion</button></form><?php endif; ?></aside>
    <?php endif; ?>
    <header class="ssf-inspector-case-heading">
        <a href="<?php echo esc_url($portal_url); ?>">← Mina inspektioner</a><div class="ssf-inspector-title"><p class="ssf-inspector-number"><?php echo esc_html($case['number']); ?></p><h1><?php echo esc_html($case['title']); ?></h1><p><?php echo esc_html($template['name'] . ' · version ' . $template['version']); ?></p></div>
        <div class="ssf-inspector-progress"><strong data-ssf-progress-label><?php echo esc_html($case['progress']['complete'] . ' av ' . $case['progress']['total'] . ' klara'); ?></strong><progress max="100" value="<?php echo esc_attr((string) $case['progress']['percent']); ?>" data-ssf-progress></progress><span id="ssf-inspection-sync" role="status">✓ Sparat</span></div>
    </header>
    <?php if ($case['task']) : ?><aside class="ssf-inspector-task"><strong>Uppdrag</strong><p><?php echo nl2br(esc_html($case['task'])); ?></p></aside><?php endif; ?>
    <?php if ($readonly && 'completed' !== ($record['status'] ?? '')) : ?><aside class="ssf-inspector-task"><strong>Inspektionen är inte bokad ännu</strong><p>Protokollet blir redigerbart när handläggaren har registrerat bokningen.</p></aside><?php endif; ?>
    <nav class="ssf-inspector-steps" aria-label="Inspektionens steg"><a href="#oversikt">Översikt</a><a href="#steg-1">1. Verifiera ansökan</a><a href="#steg-2">2. Bedöm fartyget</a><a href="#steg-3">3. Sammanfatta</a></nav>

    <section id="oversikt" class="ssf-inspector-panel">
        <h2>Översikt</h2><div class="ssf-inspector-detail-grid"><div><span>Fartygsombud</span><strong><?php echo esc_html($snapshot['applicant_name'] ?: 'Ej angivet'); ?></strong></div><div><span>Ägare / organisation</span><strong><?php echo esc_html($snapshot['applicant_organization'] ?: 'Ej angivet'); ?></strong></div><div><span>Signal / reg.nr</span><strong><?php echo esc_html($snapshot['registry_number'] ?: 'Ej angivet'); ?></strong></div><div><span>Inspektörer</span><strong><?php echo esc_html(implode(' · ', array_filter(array($case['lead_name'], $case['co_name'])))); ?></strong></div><div><span>Bokning</span><strong><?php echo esc_html(trim(($case['booking']['date'] ?? '') . ' ' . ($case['booking']['start'] ?? '')) ?: 'Inte bokad'); ?></strong><small><?php echo esc_html(implode(' · ', array_filter(array($case['booking']['location'] ?? '', $case['booking']['contact'] ?? '', $case['booking']['comment'] ?? '')))); ?></small></div></div>
        <div class="ssf-inspector-fields" data-ssf-details><label>Datum<input type="date" name="date" value="<?php echo esc_attr($record['details']['date'] ?? ($case['booking']['date'] ?? '')); ?>" <?php disabled($readonly); ?>></label><label>Plats<input type="text" name="place" value="<?php echo esc_attr($record['details']['place'] ?? ($case['booking']['location'] ?? '')); ?>" <?php disabled($readonly); ?>></label><label>Närvarande vid besöket<input type="text" name="attendees" value="<?php echo esc_attr($record['details']['attendees'] ?? ''); ?>" <?php disabled($readonly); ?>></label></div>
        <details><summary>Visa hela ansökans snapshot</summary><dl class="ssf-inspector-application-snapshot"><?php foreach ($snapshot as $key => $value) : if ('application_documents' === $key || '' === (string) $value) { continue; } ?><div><dt><?php echo esc_html(ucfirst(str_replace('_', ' ', $key))); ?></dt><dd><?php echo nl2br(esc_html((string) $value)); ?></dd></div><?php endforeach; ?></dl></details>
        <?php if ($case['legacy_files']) : ?><details><summary>Övriga filer</summary><ul><?php foreach ($case['legacy_files'] as $file) : ?><li><a href="<?php echo esc_url($file['url']); ?>" target="_blank" rel="noopener"><?php echo esc_html(get_the_title($file['id']) ?: $file['label']); ?></a> <small><?php echo esc_html($file['label'] . ($file['note'] ? ' · ' . $file['note'] : '')); ?></small></li><?php endforeach; ?></ul></details><?php endif; ?>
    </section>

    <?php foreach ($template['sections'] as $section) : ?>
        <section id="steg-<?php echo esc_attr((string) $section['step']); ?>" class="ssf-inspector-panel ssf-inspector-step">
            <?php if (3 === (int) $section['step']) : ?>
                <p class="ssf-inspector-kicker">Steg 3</p><h2>Sammanfatta</h2><div class="ssf-inspector-summary-stats"><div><strong><?php echo esc_html((string) count($questions)); ?></strong><span>kontrollpunkter</span></div><div><strong><?php echo esc_html((string) ($case['progress']['complete'] - count($case['deviations']))); ?></strong><span>utan noterad avvikelse</span></div><div><strong><?php echo esc_html((string) count($case['deviations'])); ?></strong><span>att granska</span></div></div>
                <?php if ($case['deviations']) : ?><div class="ssf-inspector-review-list"><h3>Punkter att granska</h3><?php foreach ($case['deviations'] as $deviation) : ?><a href="#fraga-<?php echo esc_attr($deviation['id']); ?>"><strong><?php echo esc_html(strtoupper($deviation['id'])); ?></strong><span><?php echo esc_html($deviation['answer']); ?></span></a><?php endforeach; ?></div><?php endif; ?>
            <?php else : ?><p class="ssf-inspector-kicker">Steg <?php echo esc_html((string) $section['step']); ?></p><h2><?php echo esc_html(1 === (int) $section['step'] ? 'Verifiera ansökan' : 'Bedöm fartyget'); ?></h2><p><?php echo 1 === (int) $section['step'] ? 'Jämför uppgifterna med det du ser och med tillgängliga underlag. Ansökan är skrivskyddad.' : 'Bedöm den historiska karaktären ombord och dokumentera avvikelser.'; ?></p><?php endif; ?>
            <h3><?php echo esc_html($section['title']); ?></h3>
            <?php foreach ($section['questions'] as $question) : $answer = (array) ($record['answers'][$question['id']] ?? array()); $context = SSF_Medlemsprocess_Inspection::context($record, $question); ?>
                <article id="fraga-<?php echo esc_attr($question['id']); ?>" class="ssf-inspector-question" data-ssf-question="<?php echo esc_attr($question['id']); ?>" data-required-comments="<?php echo esc_attr(wp_json_encode($question['comment_required_for'])); ?>">
                    <p class="ssf-inspector-question-number">Fråga <?php echo esc_html(strtoupper($question['id'])); ?></p><h4><?php echo esc_html($question['text']); ?></h4><?php if ($question['help']) : ?><p class="ssf-inspector-help"><?php echo esc_html($question['help']); ?></p><?php endif; ?>
                    <?php if ($context) : ?><aside class="ssf-inspector-context"><strong>Sökanden uppgav</strong><dl><?php foreach ($context as $item) : ?><div><dt><?php echo esc_html($item['label']); ?></dt><dd><?php echo nl2br(esc_html($item['value'])); ?></dd></div><?php endforeach; ?></dl></aside><?php endif; ?>
                    <fieldset <?php disabled($readonly); ?>><legend>Din bedömning</legend><div class="ssf-inspector-options"><?php foreach ($question['options'] as $index => $option) : $input_id = 'ssf-' . $case['inspection_id'] . '-' . $question['id'] . '-' . $index; ?><label for="<?php echo esc_attr($input_id); ?>"><input id="<?php echo esc_attr($input_id); ?>" type="radio" name="answer-<?php echo esc_attr($question['id']); ?>" value="<?php echo esc_attr($option); ?>" <?php checked($answer['selected_option'] ?? '', $option); ?>><span><?php echo esc_html($option); ?></span></label><?php endforeach; ?></div></fieldset>
                    <button type="button" class="ssf-inspector-comment-toggle" aria-expanded="<?php echo empty($answer['comment']) ? 'false' : 'true'; ?>" <?php disabled($readonly); ?>><?php echo empty($answer['comment']) ? 'Lägg till kommentar' : 'Redigera kommentar'; ?></button>
                    <label class="ssf-inspector-comment <?php echo empty($answer['comment']) ? '' : 'is-open'; ?>"><span>Kommentar <em data-comment-required></em></span><textarea rows="3" <?php disabled($readonly); ?>><?php echo esc_textarea($answer['comment'] ?? ''); ?></textarea></label>
                    <div class="ssf-inspector-photo-actions"><label class="ssf-process-button ssf-process-button--secondary <?php echo $readonly ? 'is-disabled' : ''; ?>">Ta foto<input class="ssf-inspector-photo-input" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" <?php disabled($readonly); ?>></label><label class="ssf-process-button ssf-process-button--secondary <?php echo $readonly ? 'is-disabled' : ''; ?>">Välj bild<input class="ssf-inspector-photo-input" type="file" accept="image/jpeg,image/png,image/webp" <?php disabled($readonly); ?>></label></div>
                    <div class="ssf-inspector-photos"><?php foreach ((array) $record['photos'] as $photo) : if (($photo['question_id'] ?? '') !== $question['id']) { continue; } ?><figure data-photo-id="<?php echo esc_attr($photo['id']); ?>"><img src="<?php echo esc_url($this->photo_url($case['inspection_id'], $photo['id'])); ?>" alt="<?php echo esc_attr($photo['caption'] ?: 'Inspektionsbild'); ?>"><figcaption><input type="text" value="<?php echo esc_attr($photo['caption']); ?>" placeholder="Bildtext" <?php disabled($readonly); ?>><button type="button" data-delete-photo <?php disabled($readonly); ?>>Ta bort</button></figcaption></figure><?php endforeach; ?></div>
                </article>
            <?php endforeach; ?>
            <?php if (3 === (int) $section['step']) : ?><label class="ssf-inspector-summary"><span>Kort sammanfattning / motivering <em>Obligatorisk</em></span><textarea rows="7" data-ssf-summary <?php disabled($readonly); ?>><?php echo esc_textarea($record['summary'] ?? ''); ?></textarea></label><?php endif; ?>
        </section>
    <?php endforeach; ?>

    <section class="ssf-inspector-panel"><h2>Översiktsbilder</h2><p>Rekommenderat men inte blockerande.</p><div class="ssf-inspector-overview-photos"><?php foreach ($template['overview_photos'] as $key => $label) : ?><div class="ssf-inspector-question" data-ssf-question="<?php echo esc_attr($key); ?>"><h3><?php echo esc_html($label); ?></h3><label class="ssf-process-button ssf-process-button--secondary <?php echo $readonly ? 'is-disabled' : ''; ?>">Ta eller välj bild<input class="ssf-inspector-photo-input" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" <?php disabled($readonly); ?>></label><div class="ssf-inspector-photos"><?php foreach ((array) $record['photos'] as $photo) : if (($photo['question_id'] ?? '') !== $key) { continue; } ?><figure data-photo-id="<?php echo esc_attr($photo['id']); ?>"><img src="<?php echo esc_url($this->photo_url($case['inspection_id'], $photo['id'])); ?>" alt="<?php echo esc_attr($photo['caption'] ?: $label); ?>"><figcaption><input type="text" value="<?php echo esc_attr($photo['caption']); ?>" placeholder="Bildtext" <?php disabled($readonly); ?>><button type="button" data-delete-photo <?php disabled($readonly); ?>>Ta bort</button></figcaption></figure><?php endforeach; ?></div></div><?php endforeach; ?></div></section>

    <section class="ssf-inspector-panel ssf-inspector-finalize"><h2><?php echo $readonly ? 'Färdigt protokoll' : 'Färdigställ'; ?></h2><p><?php echo esc_html($template['disclaimer']); ?></p>
    <?php if (! $readonly && $case['is_lead'] && 'draft' === $record['status']) : ?><button class="ssf-process-button" type="button" data-workflow="ready">Klar för bekräftelse</button><?php endif; ?>
    <?php if (! $readonly && $case['is_co'] && 'ready_confirmation' === $record['status']) : ?><label class="ssf-inspector-confirm"><input type="checkbox" data-co-confirm> Jag har deltagit i inspektionen och står bakom protokollet.</label><button class="ssf-process-button" type="button" data-workflow="confirm">Bekräfta</button><?php endif; ?>
    <?php if (! $readonly && $case['is_lead'] && 'ready_finalization' === $record['status']) : ?><button class="ssf-process-button" type="button" data-workflow="finalize">Färdigställ och lås protokollet</button><?php endif; ?>
    <?php if ('ready_confirmation' === $record['status'] && $case['is_lead']) : ?><p>Väntar på bekräftelse från <?php echo esc_html($case['co_name']); ?>.</p><?php endif; ?>
    <?php if ($readonly) : ?><p><strong>Färdigställt <?php echo esc_html(mysql2date('j F Y H:i', $record['completed_at'])); ?></strong></p><button class="ssf-process-button ssf-process-button--secondary" type="button" onclick="window.print()">Skriv ut / spara som PDF</button><?php endif; ?>
    </section>
<?php endif; ?>
</section>
