<?php
/** @var SSF_Medlemsprocess_Inspector $this */
if (! defined('ABSPATH')) { exit; }
$user = wp_get_current_user();
$notice_messages = array(
    'draft' => 'Utkastet har sparats.',
    'complete' => 'Inspektionsrapporten är markerad som klar.',
    'message' => 'Meddelandet har skickats och sparats i ärendet.',
);
?>
<section class="ssf-inspector-shell">
    <header class="ssf-inspector-header">
        <div><p class="ssf-inspector-kicker">SSF medlemsprocess</p><h1>Mina inspektioner</h1><p>Inloggad som <?php echo esc_html($user->display_name); ?></p></div>
        <?php if ('case' === $view) : ?><a class="ssf-process-button ssf-process-button--secondary" href="<?php echo esc_url($portal_url); ?>">Till översikten</a><?php endif; ?>
    </header>
    <?php if (isset($notice_messages[$notice])) : ?><div class="ssf-inspector-notice" role="status"><?php echo esc_html($notice_messages[$notice]); ?></div><?php endif; ?>
    <?php if ('checklist' === $error) : ?><div class="ssf-inspector-notice ssf-inspector-notice--warning" role="alert">Alla kontrollpunkter och rekommendation måste vara ifyllda innan rapporten kan markeras som klar. <?php echo ! empty($_GET['missing']) ? esc_html((string) absint($_GET['missing'])) . ' kontrollpunkter återstår.' : ''; ?></div><?php endif; ?>
    <?php if ('message' === $error) : ?><div class="ssf-inspector-notice ssf-inspector-notice--warning" role="alert">Skriv ett meddelande innan du skickar.</div><?php endif; ?>

    <?php if ('dashboard' === $view) : ?>
        <?php
        $counts = array('total' => count($cases), 'draft' => 0, 'complete' => 0, 'overdue' => 0);
        foreach ($cases as $item) {
            $state = $item['report']['status'] ?? 'not_started';
            if ('draft' === $state) { $counts['draft']++; }
            if ('complete' === $state) { $counts['complete']++; }
            if ($item['deadline'] && strtotime($item['deadline']) < strtotime(current_time('Y-m-d')) && 'complete' !== $state) { $counts['overdue']++; }
        }
        ?>
        <div class="ssf-inspector-metrics" aria-label="Sammanfattning"><div><span>Tilldelade</span><strong><?php echo esc_html((string) $counts['total']); ?></strong></div><div><span>Utkast</span><strong><?php echo esc_html((string) $counts['draft']); ?></strong></div><div><span>Klara</span><strong><?php echo esc_html((string) $counts['complete']); ?></strong></div><div><span>Försenade</span><strong><?php echo esc_html((string) $counts['overdue']); ?></strong></div></div>
        <?php if (! $cases) : ?>
            <div class="ssf-inspector-empty"><h2>Inga tilldelade ärenden</h2><p>När en handläggare tilldelar dig en inspektion visas den här.</p></div>
        <?php else : ?>
            <div class="ssf-inspector-case-list">
                <?php foreach ($cases as $item) : $state = $item['report']['status'] ?? 'not_started'; ?>
                    <article class="ssf-inspector-case-card">
                        <div class="ssf-inspector-case-card__main"><div class="ssf-inspector-card-heading"><span class="ssf-inspector-number"><?php echo esc_html($item['number']); ?></span><span class="ssf-inspector-status ssf-inspector-status--<?php echo esc_attr($state); ?>"><?php echo esc_html('complete' === $state ? 'Rapport klar' : ('draft' === $state ? 'Utkast' : 'Ej påbörjad')); ?></span></div><h2><a href="<?php echo esc_url($item['url']); ?>"><?php echo esc_html($item['data']['ship_name'] ?? $item['title']); ?></a></h2><p><?php echo esc_html($item['status_label']); ?><?php echo ! empty($item['data']['ship_home_port']) ? ' · ' . esc_html($item['data']['ship_home_port']) : ''; ?></p></div>
                        <div class="ssf-inspector-case-card__meta"><span>Klart senast</span><strong class="<?php echo $item['deadline'] && strtotime($item['deadline']) < strtotime(current_time('Y-m-d')) && 'complete' !== $state ? 'is-overdue' : ''; ?>"><?php echo esc_html($item['deadline'] ? wp_date('j F Y', strtotime($item['deadline'])) : 'Ej angivet'); ?></strong><?php if ($item['task']) : ?><small><?php echo esc_html($item['task']); ?></small><?php endif; ?></div>
                        <a class="ssf-process-button" href="<?php echo esc_url($item['url']); ?>">Öppna ärende</a>
                    </article>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>
    <?php else : ?>
        <?php $data = $case['data']; $inspection = $case['inspection']; $checks = $inspection['checks']; ?>
        <div class="ssf-inspector-case-heading"><div><p class="ssf-inspector-number"><?php echo esc_html($case['number']); ?></p><h2><?php echo esc_html($data['ship_name'] ?? $case['title']); ?></h2><p><?php echo esc_html($case['status_label']); ?><?php echo $case['deadline'] ? ' · Önskat klart: ' . esc_html(wp_date('j F Y', strtotime($case['deadline'])) : ''; ?></p></div><div class="ssf-inspector-progress" aria-label="Checklistans framsteg"><strong data-ssf-progress-label><?php echo esc_html($case['progress']['complete'] . ' av ' . $case['progress']['total']); ?></strong><span><i data-ssf-progress-bar style="width:<?php echo esc_attr((string) $case['progress']['percent']); ?>%"></i></span></div></div>
        <?php if ($case['task']) : ?><div class="ssf-inspector-task"><strong>Uppdrag</strong><p><?php echo nl2br(esc_html($case['task'])); ?></p></div><?php endif; ?>
        <nav class="ssf-inspector-tabs" aria-label="Ärendedelar"><button type="button" class="is-active" data-ssf-inspector-tab="overview">Översikt</button><button type="button" data-ssf-inspector-tab="application">Ansökan</button><button type="button" data-ssf-inspector-tab="ship">Fartyg</button><button type="button" data-ssf-inspector-tab="checklist">Checklista</button><button type="button" data-ssf-inspector-tab="files">Filer</button><button type="button" data-ssf-inspector-tab="communication">Kommunikation</button><button type="button" data-ssf-inspector-tab="report">Bedömning</button><button type="button" data-ssf-inspector-tab="history">Historik</button></nav>
        <form class="ssf-inspector-report" method="post" enctype="multipart/form-data" action="<?php echo esc_url(admin_url('admin-post.php')); ?>">
            <input type="hidden" name="action" value="ssf_inspector_save_report"><input type="hidden" name="application_id" value="<?php echo esc_attr((string) $case['id']); ?>"><?php wp_nonce_field('ssf_inspector_report_' . $case['id']); ?>
            <section class="ssf-inspector-panel is-active" data-ssf-inspector-panel="overview"><h3>Översikt</h3><div class="ssf-inspector-detail-grid"><div><span>Fartygsombud</span><strong><?php echo esc_html($data['applicant_name'] ?? 'Ej angivet'); ?></strong><a href="mailto:<?php echo esc_attr($data['applicant_email'] ?? ''); ?>"><?php echo esc_html($data['applicant_email'] ?? ''); ?></a><a href="tel:<?php echo esc_attr($data['applicant_phone'] ?? ''); ?>"><?php echo esc_html($data['applicant_phone'] ?? ''); ?></a></div><div><span>Bokning</span><strong><?php echo esc_html(! empty($case['booking']['date']) ? $case['booking']['date'] . ' ' . ($case['booking']['start'] ?? '') : 'Ingen bokning registrerad'); ?></strong><p><?php echo esc_html($case['booking']['location'] ?? ''); ?></p></div><div><span>Din rapport</span><strong><?php echo esc_html('complete' === ($case['report']['status'] ?? '') ? 'Klar' : ('draft' === ($case['report']['status'] ?? '') ? 'Utkast' : 'Ej påbörjad')); ?></strong><p><?php echo ! empty($case['report']['updated_at']) ? esc_html('Senast sparad ' . mysql2date('j F Y H:i', $case['report']['updated_at'])) : ''; ?></p></div></div></section>
            <section class="ssf-inspector-panel" data-ssf-inspector-panel="application"><h3>Ansökan</h3><div class="ssf-inspector-read-table"><div><span>Organisation eller rederi</span><strong><?php echo esc_html($data['applicant_organization'] ?? ''); ?></strong></div><div><span>Adress</span><strong><?php echo nl2br(esc_html($data['applicant_address'] ?? '')); ?></strong></div><div><span>Webbplats</span><strong><?php echo esc_html($data['applicant_website'] ?? ''); ?></strong></div><div><span>Ansökningsväg</span><strong><?php echo esc_html($data['application_path'] ?? ''); ?></strong></div></div></section>
            <section class="ssf-inspector-panel" data-ssf-inspector-panel="ship"><h3>Fartygsuppgifter</h3><div class="ssf-inspector-read-table"><div><span>Typ och rigg</span><strong><?php echo esc_html(trim(($data['ship_type'] ?? '') . ' ' . ($data['ship_rig'] ?? ''))); ?></strong></div><div><span>Byggår och varv</span><strong><?php echo esc_html(trim(($data['ship_build_year'] ?? '') . ' ' . ($data['ship_shipyard'] ?? ''))); ?></strong></div><div><span>Mått</span><strong><?php echo esc_html('L ' . ($data['ship_length'] ?? '-') . ', B ' . ($data['ship_beam'] ?? '-') . ', D ' . ($data['ship_draft'] ?? '-')); ?></strong></div><div><span>Hemmahamn</span><strong><?php echo esc_html($data['ship_home_port'] ?? ''); ?></strong></div><div class="is-wide"><span>Historia</span><strong><?php echo nl2br(esc_html($data['ship_history'] ?? '')); ?></strong></div><div class="is-wide"><span>Nuvarande användning</span><strong><?php echo nl2br(esc_html($data['ship_current_use'] ?? '')); ?></strong></div><div class="is-wide"><span>Beskrivning</span><strong><?php echo nl2br(esc_html($data['ship_description'] ?? '')); ?></strong></div></div></section>
            <section class="ssf-inspector-panel" data-ssf-inspector-panel="checklist"><div class="ssf-inspector-panel-heading"><div><h3>Inspektionschecklista</h3><p>Varje punkt behöver en bedömning för att rapporten ska kunna markeras som klar.</p></div><span data-ssf-progress-summary><?php echo esc_html($case['progress']['complete'] . ' av ' . $case['progress']['total'] . ' bedömda'); ?></span></div><div class="ssf-inspector-inspection-grid"><label>Datum<input type="date" name="ssf_inspection[date]" value="<?php echo esc_attr($inspection['date'] ?? ''); ?>"></label><label>Plats<input type="text" name="ssf_inspection[place]" value="<?php echo esc_attr($inspection['place'] ?? ''); ?>"></label><label>Inspektör<input type="text" name="ssf_inspection[inspector]" value="<?php echo esc_attr($inspection['inspector'] ?? $user->display_name); ?>"></label><label>Närvarande<input type="text" name="ssf_inspection[attendees]" value="<?php echo esc_attr($inspection['attendees'] ?? ''); ?>"></label><label>Typ<select name="ssf_inspection[type]"><?php foreach (array('Ombord', 'Dokumentgranskning', 'Digital genomgång', 'Annat') as $type) : ?><option value="<?php echo esc_attr($type); ?>" <?php selected($inspection['type'] ?? '', $type); ?>><?php echo esc_html($type); ?></option><?php endforeach; ?></select></label><label>Väder eller förhållanden<input type="text" name="ssf_inspection[conditions]" value="<?php echo esc_attr($inspection['conditions'] ?? ''); ?>"></label></div><?php foreach (SSF_Medlemsprocess_Inspector::checklist_sections() as $section => $points) : ?><details class="ssf-inspector-check-section" open><summary><?php echo esc_html($section); ?><span><?php echo esc_html((string) count($points)); ?> punkter</span></summary><?php foreach ($points as $key => $label) : $value = (array) ($checks[$key] ?? array()); ?><div class="ssf-inspector-check-row"><label><strong><?php echo esc_html($label); ?></strong><select name="ssf_inspection[checks][<?php echo esc_attr($key); ?>][status]" data-ssf-check-status><?php foreach (array('' => 'Välj bedömning', 'met' => 'Uppfyllt', 'not_met' => 'Uppfyller ej', 'completion' => 'Komplettering krävs', 'na' => 'Ej relevant') as $status_key => $status_label) : ?><option value="<?php echo esc_attr($status_key); ?>" <?php selected($value['status'] ?? '', $status_key); ?>><?php echo esc_html($status_label); ?></option><?php endforeach; ?></select></label><label><span>Kommentar</span><textarea name="ssf_inspection[checks][<?php echo esc_attr($key); ?>][comment]" rows="2"><?php echo esc_textarea($value['comment'] ?? ''); ?></textarea></label></div><?php endforeach; ?></details><?php endforeach; ?></section>
            <section class="ssf-inspector-panel" data-ssf-inspector-panel="files"><h3>Filer och bilder</h3><?php if ($case['files']) : ?><ul class="ssf-inspector-files"><?php foreach ($case['files'] as $file) : ?><li><a href="<?php echo esc_url(wp_get_attachment_url((int) $file['id'])); ?>" target="_blank" rel="noopener"><?php echo esc_html(get_the_title((int) $file['id'])); ?></a><span><?php echo esc_html('application' === $file['source'] ? 'Ansökan' : ('completion' === $file['source'] ? 'Komplettering' : 'Inspektörsfil')); ?></span><?php if (! empty($file['note'])) : ?><small><?php echo esc_html($file['note']); ?></small><?php endif; ?></li><?php endforeach; ?></ul><?php else : ?><p>Inga filer finns i ärendet.</p><?php endif; ?><div class="ssf-inspector-upload"><label>Lägg till bilder eller PDF<input type="file" name="ssf_inspector_files[]" accept=".jpg,.jpeg,.png,.webp,.pdf" multiple></label><label>Filkommentar<input type="text" name="ssf_inspector_file_note" placeholder="Exempel: Bild av akterdäck"></label><label class="ssf-inspector-checkbox"><input type="checkbox" name="ssf_inspector_files_visible" value="1"> Sökanden kan se filerna via statuslänken</label></div></section>
            <section class="ssf-inspector-panel" data-ssf-inspector-panel="report"><h3>Samlad bedömning</h3><div class="ssf-inspector-text-grid"><?php foreach (array('summary' => 'Sammanfattning', 'strengths' => 'Styrkor', 'deficiencies' => 'Brister', 'actions' => 'Rekommenderade åtgärder', 'board_comment' => 'Intern kommentar till handläggare/styrelse', 'public_comment' => 'Kommentar till sökanden') as $key => $label) : ?><label><?php echo esc_html($label); ?><textarea name="ssf_inspection[<?php echo esc_attr($key); ?>]" rows="4"><?php echo esc_textarea($inspection[$key] ?? ''); ?></textarea></label><?php endforeach; ?></div><label class="ssf-inspector-recommendation">Rekommendation<select name="ssf_inspection[recommendation]"><option value="">Välj rekommendation</option><?php foreach (array('Rekommenderas för godkännande', 'Rekommenderas som aspirant', 'Komplettering krävs', 'Rekommenderas ej') as $recommendation) : ?><option value="<?php echo esc_attr($recommendation); ?>" <?php selected($inspection['recommendation'] ?? '', $recommendation); ?>><?php echo esc_html($recommendation); ?></option><?php endforeach; ?></select></label></section>
            <section class="ssf-inspector-panel" data-ssf-inspector-panel="history"><h3>Historik</h3><?php if ($case['history']) : ?><ol class="ssf-inspector-history"><?php foreach (array_reverse($case['history']) as $item) : ?><li><strong><?php echo esc_html(mysql2date('j F Y, H:i', $item['time'] ?? '')); ?></strong><span><?php echo esc_html($item['public'] ?? false ? 'Meddelande till sökanden' : 'Ärendehändelse'); ?></span><p><?php echo nl2br(esc_html($item['message'] ?? '')); ?></p></li><?php endforeach; ?></ol><?php else : ?><p>Ingen synlig historik ännu.</p><?php endif; ?></section>
            <div class="ssf-inspector-report-actions"><button class="ssf-process-button ssf-process-button--secondary" type="submit" name="report_action" value="draft">Spara utkast</button><button class="ssf-process-button" type="submit" name="report_action" value="complete" data-ssf-complete-report>Markera rapport som klar</button></div>
        </form>
        <section class="ssf-inspector-panel ssf-inspector-communication" data-ssf-inspector-panel="communication"><h3>Kommunikation med sökanden</h3><p>Meddelandet sparas i ärendet och blir synligt via sökandens statuslänk.</p><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="ssf_inspector_send_message"><input type="hidden" name="application_id" value="<?php echo esc_attr((string) $case['id']); ?>"><?php wp_nonce_field('ssf_inspector_message_' . $case['id']); ?><label>Meddelande<textarea name="message" rows="5" required></textarea></label><div class="ssf-inspector-message-options"><label class="ssf-inspector-checkbox"><input type="checkbox" name="requires_completion" value="1"> Begär komplettering och uppdatera ärendestatus</label><label class="ssf-inspector-checkbox"><input type="checkbox" name="send_email" value="1" checked> Skicka även till <?php echo esc_html($data['applicant_email'] ?? 'sökanden'); ?> via e-post</label></div><button class="ssf-process-button" type="submit">Skicka meddelande</button></form></section>
    <?php endif; ?>
</section>
